services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webcal-cmp-push
    ports:
      - "${CONTAINER_PORT}:8080"
    environment:
      CALENDAR_URL: ${CALENDAR_URL}
      NTFY_TOPIC: ${NTFY_TOPIC}
      CALENDAR_PROXY_ENABLED: ${EXT_ENABLED}
      CALENDAR_PROXY_HOST: ${EXT_HOST}
      CALENDAR_PROXY_PORT: ${EXT_PORT}
      CALENDAR_PROXY_USERNAME: ${EXT_USERNAME}
      CALENDAR_PROXY_PASSWORD: ${EXT_PASSWORD}
      CALENDAR_CLASS: ${CALENDAR_CLASS}
      CALENDAR_KEY: ${CALENDAR_KEY}
    restart: unless-stopped
