<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.1.1</version>
	</parent>

	<groupId>lu.kbra</groupId>
	<artifactId>webcal-cmp-push</artifactId>
	<version>0.1</version>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<start-class>lu.kbra.webcal_cmp.WMain</start-class>
		<java.version>21</java.version>
		<docker.image.prefix>${project.groupId}</docker.image.prefix>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>lu.kbra</groupId>
				<artifactId>pclib</artifactId>
				<version>1.2.1</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-cache</artifactId>
		</dependency>

		<dependency>
			<groupId>com.github.ben-manes.caffeine</groupId>
			<artifactId>caffeine</artifactId>
		</dependency>

		<dependency>
			<groupId>org.apache.httpcomponents.client5</groupId>
			<artifactId>httpclient5</artifactId>
		</dependency>

		<dependency>
			<groupId>org.mnode.ical4j</groupId>
			<artifactId>ical4j</artifactId>
			<version>4.0.8</version>
		</dependency>
		<dependency>
			<groupId>lu.kbra</groupId>
			<artifactId>pclib-common</artifactId>
		</dependency>
		<dependency>
			<groupId>lu.kbra</groupId>
			<artifactId>pclib-function</artifactId>
		</dependency>
		<dependency>
			<groupId>lu.kbra</groupId>
			<artifactId>pclib-datastruct</artifactId>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
	</dependencies>

	<build>
		<finalName>${project.artifactId}</finalName>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<parameters>true</parameters>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>format</id>
			<build>
				<plugins>
					<plugin>
						<groupId>com.diffplug.spotless</groupId>
						<artifactId>spotless-maven-plugin</artifactId>
						<version>3.9.0</version>
						<configuration>
							<java>
								<eclipse>
									<file>
										https://raw.githubusercontent.com/UnKabaraQuiDev/PCLib/main/eclipse-format.xml
									</file>
								</eclipse>
								<removeUnusedImports />
								<importOrder>
									<order>java,javax,org,com,lu</order>
								</importOrder>
								<trimTrailingWhitespace />
								<endWithNewline />
							</java>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
	</profiles>

</project>