spring:
  application:
    name: webcal-cmp

server:
  port: 8080
  forward-headers-strategy: framework

calendar:
  url: ""
  class: ""
  zone: "Europe/Luxembourg"
  key: ""
  proxy:
    enabled: true
    host: ""
    port: 3128
    username: ""
    password: ""

nfty:
  topic: ""

logging:
  level:
    net.fortuna.ical4j.data.CalendarOutputter: ERROR